apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: configure-frontend
          image: nginx:alpine
          env:
            - name: HEADER_TITLE
              value: "Container frontend"
            - name: HEADER_COLOR
              value: "red"
            - name: FRONT
              value: https://raw.githubusercontent.com/fl64/dvp-demo-app/master/apps/frontend/index.html
          command:
            - sh
            - -c
            - "curl ${FRONT} | sed \"s|%%HEADER_TITLE%%|${HEADER_TITLE}|g\" > /usr/share/nginx/html/index.html && sed -i \"s|%%HEADER_COLOR%%|${HEADER_COLOR}|g\" /usr/share/nginx/html/index.html"
          volumeMounts:
            - name: frontend-config-volume
              mountPath: /config
            - name: nginx-html-volume
              mountPath: /usr/share/nginx/html
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 10m
              memory: 50Mi
      containers:
        - name: nginx
          env:
            - name: HEADER_TITLE
              value: "Custom Frontend Title"
            - name: HEADER_COLOR
              value: "red"
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-html-volume
              mountPath: /usr/share/nginx/html
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 10m
              memory: 50Mi
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-config # Имя ConfigMap
            items:
              - key: index.html
                path: index.html # Монтируем index.html из ConfigMap
        - name: nginx-html-volume
          emptyDir: {}
