apiVersion: network.deckhouse.io/v1alpha1
kind: ServiceWithHealthchecks
metadata:
  name: frontend-hp
  namespace: default
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
  healthcheck:
    probes:
      - mode: HTTP
        http:
          targetPort: 80
          path: /
