apiVersion: virtualization.deckhouse.io/v1alpha2
kind: VirtualDisk
metadata:
  name: root-disk-backend
  labels:
    app: backend
spec:
  persistentVolumeClaim:
    size: 4G
    storageClassName: i-linstor-thin-r1 # linstor-thin-r2
  dataSource:
    type: ObjectRef
    objectRef:
      kind: ClusterVirtualImage
      name: demo-alpine-3-21
