# https://taskfile.dev

version: "3"

dotenv:
- .env

vars:
  TMP_PATH: ./tmp
  SSH_KEYS_NAME: demo
  SSH_KEYS_PATH: "{{ .TMP_PATH }}"
  SSH_PRIV_KEY_FILE: "{{ .SSH_KEYS_PATH }}/{{.SSH_KEYS_NAME}}"
  SSH_PUB_KEY_FILE: "{{ .SSH_PRIV_KEY_FILE }}.pub"

tasks:
  init:
    desc: "Create temp dirs"
    cmds:
      - mkdir -p {{ .TMP_PATH  }}
      - mkdir -p {{ .SSH_KEYS_PATH  }}
  ssh-gen:
    deps:
      - init
    desc: Generate ssh keys for VMs
    cmds:
      - echo "🚀 Generate ssh keys {{ .SSH_PRIV_KEY_FILE }}"
      - yes | ssh-keygen -t rsa -b 1024 -f "{{ .SSH_PRIV_KEY_FILE }}" -N "" -C "{{ .SSH_KEYS_NAME }}" -v
    status:
      - test -f "{{ .SSH_PRIV_KEY_FILE }}"
  update-ssh:
    vars:
      SSH_PUB_KEY:
        sh: cat "{{ .SSH_PUB_KEY_FILE }}"
    desc: Update public ssh keys in cloudinit
    deps:
      - ssh-gen
    cmds:
      - echo "🚀 Update ssh keys"
      - grep -rwl "{{ .SSH_KEYS_NAME }}" | xargs sed -i 's|ssh-rsa [^ ]* {{ .SSH_KEYS_NAME }}|{{ .SSH_PUB_KEY }}|g'
  update-password:
    desc: Update password for users
    cmds:
    - echo "🚀 Generate password hash from >>${PASSWORD}<<"
    - |
      find . -name "*.yaml" -exec yq eval --inplace 'with(select(.kind == "User"); .spec.password="'$(echo "${PASSWORD}" | htpasswd -BinC 10 "" | cut -d: -f2 | base64 -w0)'")' '{}' \;
  update-sc:
    desc: Update storage class for VM disks
    cmds:
      - |
          find . -name "*.yaml" -exec yq eval --inplace 'with(select(.kind == "VirtualDisk"); .spec.persistentVolumeClaim.storageClassName="'${STORAGE_CLASS}'")' '{}' \;
  update-fqdn:
    desc: Update FQDN for ingress and dexauthenticator
    cmds:
      - echo "🚀 Update FQDN"
      - |
          yq -i '(.spec.rules[]?.host |= env(FQDN)) | (.spec.tls[].hosts[] |= env(FQDN))' ./k8s/demo-app/ingress.yaml
          yq -i '(.spec.dnsNames[]? |= env(FQDN))' ./k8s/demo-app/cert.yaml
          yq -i '(.spec.applicationDomain |= env(FQDN))' ./k8s/demo-app/dex.yaml
  update:
    deps:
      - update-ssh
      - update-password
      - update-sc
      - update-fqdn
  deploy:
    desc: Deploy demo APP infra
    vars:
      start_time:
        sh: date +%s
    cmds:
      - task: update
      - echo "🚀 Deploy APP"
      - kubectl apply -f ./k8s/project-demo-app.yaml
      - kubectl apply -f ./k8s/project-demo-db.yaml
      - kubectl get project -o name | xargs kubectl wait --for='jsonpath={.status.state}=Deployed' --timeout=360s
      - kubectl apply -k ./k8s
      - kubectl -n demo-db get vm -o name | xargs kubectl -n demo-db wait --for='jsonpath={.status.phase}=Running' --timeout=360s
      - kubectl -n demo-app get vm -o name | xargs kubectl -n demo-app wait --for='jsonpath={.status.phase}=Running' --timeout=360s
      - |
        export end_time=$(date +%s)
        difference=$((end_time - {{.start_time}}))
        date -ud "@$difference" +'%H:%M:%S'
  undeploy:
    desc: Remove demo APP infra
    cmds:
      - kubectl delete -k ./k8s || true
      - kubectl delete -f ./k8s/project-demo-app.yaml || true
      - kubectl delete -f ./k8s/project-demo-db.yaml || true
  uptime:
    desc: Check VM's uptime via ansible
    cmds:
      - ansible -m shell -a "uptime" -i inventory.yaml all
