#cloud-config
package_update: true
package_upgrade: true
packages:
  - nginx
users:
  - name: cloud
    passwd: $6$rounds=4096$vln/.aPHBOI7BMYR$bBMkqQvuGs5Gyd/1H5DP4m9HjQSy.kgrxpaGEHwkX7KEFV8BS.HZWPitAtZ2Vd8ZqIZRqmlykRCagTgPejt1i.
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    chpasswd: {expire: False}
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDJPiE9aJL1IFP8fOZdBKW3HxGnhcRzKKw2jznutjZxyCPOepreu+UEDnKXa3bd+asylx6prib4J7rThm/+AKB8vCLIjP6l4tgr12V7rommXWO3NtES4fi3SbR8g+1V2ARDQ+SgMtXoFFMBmI9J2DZKX/kyo5MszgdeT3HLOeTsPw== demo
write_files:
  - path: /var/www/frontend/index.html
    permissions: "0644"
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>My Frontend</title>
          <!-- Подключение Bootstrap CSS -->
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
          <style>
              body {
                  padding: 20px;
              }
              table {
                  width: 100%;
              }
          </style>
      </head>
      <body>
          <div class="container">
              <h1 class="mb-4" id="header" style="color: blue;">VM frontend</h1>

              <!-- Таблица данных -->
              <div class="mb-4">
                  <h2>Data Table</h2>
                  <table class="table table-striped">
                      <thead>
                          <tr>
                              <th>ID</th>
                              <th>Name</th>
                              <th>Action</th>
                          </tr>
                      </thead>
                      <tbody id="data-table">
                      </tbody>
                  </table>
              </div>

              <!-- Форма для добавления данных -->
              <div>
                  <h2>Add New Record</h2>
                  <div class="input-group mb-3">
                      <input type="text" id="new-name" class="form-control" placeholder="Enter name">
                      <button class="btn btn-primary" onclick="addData()">Add</button>
                  </div>
              </div>
          </div>

          <!-- Подключение Bootstrap JS и Popper.js -->
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
          <script>
              // URL бэкенда
              const backendUrl = '/api';

              // Загрузка данных из бэкенда
              function fetchData() {
                  fetch(`${backendUrl}/data`)
                      .then(response => response.json())
                      .then(data => {
                          const tbody = document.getElementById('data-table');
                          tbody.innerHTML = ''; // Очистка таблицы
                          data.forEach(item => {
                              const row = document.createElement('tr');
                              row.innerHTML = `
                                  <td>${item.id}</td>
                                  <td>${item.name}</td>
                                  <td><button class="btn btn-danger btn-sm" onclick="deleteData(${item.id})">Delete</button></td>
                              `;
                              tbody.appendChild(row);
                          });
                      })
                      .catch(error => console.error('Error fetching data:', error));
              }

              // Добавление новой записи
              function addData() {
                  const name = document.getElementById('new-name').value.trim();
                  if (!name) return;

                  fetch(`${backendUrl}/data`, {
                      method: 'POST',
                      headers: { 'Content-Type': 'application/json' },
                      body: JSON.stringify({ name })
                  })
                      .then(() => {
                          fetchData(); // Обновляем данные после добавления
                          document.getElementById('new-name').value = ''; // Очищаем поле ввода
                      })
                      .catch(error => console.error('Error adding data:', error));
              }

              // Удаление записи
              function deleteData(id) {
                  if (!confirm('Are you sure you want to delete this record?')) return;

                  fetch(`${backendUrl}/data/${id}`, { method: 'DELETE' })
                      .then(() => fetchData()) // Обновляем данные после удаления
                      .catch(error => console.error('Error deleting data:', error));
              }

              // Инициализация при загрузке страницы
              document.addEventListener('DOMContentLoaded', () => {
                  const params = new URLSearchParams(window.location.search);
                  const title = params.get('title') || 'VM frontend';
                  document.getElementById('header').textContent = title;

                  fetchData(); // Загружаем данные при старте
              });
          </script>
      </body>
      </html>
  - path: /etc/nginx/http.d/default.conf
    permissions: "0644"
    content: |
      server {
          listen 80;
          server_name _;

          root /var/www/frontend;
          index index.html;

          location / {
              try_files $uri $uri/ /index.html;
          }

          location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
              expires 1d;
              add_header Cache-Control "public";
          }
      }
runcmd:
  - rc-update add nginx default
  - rc-service nginx start
final_message: "\U0001F525\U0001F525\U0001F525 The system is finally up, after $UPTIME seconds \U0001F525\U0001F525\U0001F525"
