---
apiVersion: virtualization.deckhouse.io/v1alpha2
kind: ClusterVirtualImage
metadata:
  name: demo-alpine-3-21
spec:
  dataSource:
    type: ContainerImage
    containerImage:
      image: registry-dvp.dev.flant.dev/e2e/alpine/alpine-3-21-bios-base
