---
apiVersion: deckhouse.io/v1alpha2
kind: Project
metadata:
  name: demo-db
spec:
  description: demo-db
  projectTemplateName: default
  parameters:
    resourceQuota:
      requests:
        cpu: 20
        memory: 20Gi
      limits:
        cpu: 20
        memory: 20Gi
    administrators:
      - subject: Group
        name: demo-db-admins
---
apiVersion: deckhouse.io/v1alpha1
kind: Group
metadata:
  name: demo-db-admins
spec:
  members:
    - kind: User
      name: demo-db-admin
  name: demo-db-admins
---
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: demo-db-admin
spec:
  email: demo-db-admin@flant.com
  password: JDJ5JDEwJHVDeklIVEVNVkV2UE00bGxLdUozdXV6WVRtWjllaTZNRjNzdU9mOXJENVd5bTY0dlk4Z3FxCgo=
---
apiVersion: deckhouse.io/v1
kind: ClusterAuthorizationRule
metadata:
  name: demo-db-admin
spec:
  accessLevel: Admin
  allowScale: true
  allowAccessToSystemNamespaces: false
  portForwarding: false
  subjects:
    - kind: Group
      name: demo-db-admins
  namespaceSelector:
    labelSelector:
      matchLabels:
        kubernetes.io/metadata.name: demo-db
