---
apiVersion: deckhouse.io/v1alpha1
kind: Group
metadata:
  name: demo-users
spec:
  members:
    - kind: User
      name: demo-user
  name: demo-users
---
apiVersion: deckhouse.io/v1
kind: User
metadata:
  name: demo-user
spec:
  email: demo-user@flant.com
  # echo "demodemodemo" | htpasswd -BinC 10 "" | cut -d: -f2 | base64 -w0
  password: JDJ5JDEwJEl6WmVXclZwYTBYeGFuUW1oZU5jMS52S0ZiL1RrOXFmbE55b3pvdWdUckxzaUo3Lmh4RnhXCgo=
---
apiVersion: deckhouse.io/v1alpha1
kind: AuthorizationRule
metadata:
  name: demo-user
  namespace: default
spec:
  accessLevel: User
  allowScale: false
  portForwarding: false
  subjects:
    - kind: Group
      name: demo-users
