apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./overlays/backend-a
  - ./overlays/backend-b
  - ./svc.yaml
  # - ./svchp.yaml
  - ./np-backend.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: cloud-init-backend
    files:
      - userdata=cfg/cloudinit.yaml
    type: provisioning.virtualization.deckhouse.io/cloud-init
configurations:
  - transformer.yaml
