apiVersion: deckhouse.io/v1
kind: DexAuthenticator
metadata:
  name: demo-app
spec:
  applicationDomain: "dc.pt.dvp.flant.dev"
  sendAuthorizationHeader: false
  applicationIngressCertificateSecretName: "frontend"
  applicationIngressClassName: "nginx"
  keepUsersLoggedInFor: "720h"
  allowedGroups:
    - demo-users
    # whitelistSourceRanges:
    # - 1.1.1.1/32
    # - 192.168.0.0/24
