apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
    - default:
        cpu: 20m
        memory: 512Mi
      defaultRequest:
        cpu: 10m
        memory: 256Mi
      type: Container
