apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - name: demo-app
          - name: demo-db
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      labels:
        app.kubernetes.io/name: '{{name}}'
        app.kubernetes.io/component: application
        # finalizers:
        #   - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/fl64/dvp-demo-app.git
        targetRevision: HEAD
        path: k8s/{{name}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
          - PrunePropagationPolicy=background
          - RespectIgnoreDifferences=false
          - ApplyOutOfSyncOnly=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
