apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-projects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/component: projects
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/fl64/dvp-demo-app.git
    targetRevision: HEAD
    path: k8s/projects
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
