apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-config-volume
              mountPath: /usr/share/nginx/html
          resources:
            limits:
              cpu: 10m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-config # Имя ConfigMap
            items:
              - key: index.html
                path: index.html # Монтируем index.html из ConfigMap
