apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deploy.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: frontend-config
    files:
      - index.html=cfg/index.html
